server:
  port: 9999
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: PLAN-MANAGER
          uri: http://localhost:8081
          predicates:
            - Path=/plan/**



