server:
  port: 8081

spring:

  application:
    name: PLAN-MANAGER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.100.41:3306/test
    username: root

  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 34.133.241.170
    password:
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://34.64.54.36:8761//eureka
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


